Indent jam script

diff --git a/jam b/jam
--- a/jam
+++ b/jam
@@ -4,11 +4,11 @@ REL="$(dirname "$0")"
 ABS="$(cd "$REL"; pwd)"
 
 if [ -f "$REL/.jam" ]; then
-	source "$REL/.jam"
+    source "$REL/.jam"
 fi
 
 gambitinstall () {
-	[ -n "${GAMBITDIR:+x}" ] && echo "$GAMBITDIR" || echo "$REL/foreign/gambit"
+    [ -n "${GAMBITDIR:+x}" ] && echo "$GAMBITDIR" || echo "$REL/foreign/gambit"
 }
 
 GAMBITSOURCE="$REL/gambit"
@@ -39,7 +39,7 @@ gambit_configure () {
 gambit_make () {
     ( [ -f "$GAMBITSOURCE/config.status" ] || gambit_configure ) &&
     cd "$GAMBITSOURCE" &&
-	make $(jobs) from-scratch
+    make $(jobs) from-scratch
 }
 
 gambit_install () {
@@ -66,34 +66,34 @@ gambit () {
 
 gambit_dispatch () {
     case "$1" in
-	"init" )
-	    gambit_init
-	    ;;
-	"update" )
-	    gambit_update
-	    ;;
-	"configure" )
-	    gambit_configure
-	    ;;
-	"make" )
-	    gambit_make
-	    ;;
-	"install" )
-	    gambit_install
-	    ;;
-	"clean" )
-	    gambit_clean
-	    ;;
-	"realclean" )
-	    gambit_realclean
-	    ;;
-	"" )
-	    gambit
-	    ;;
-	* )
-	    echo "Unknown gambit option : $1"
-	    return 1
-	    ;;
+    "init" )
+        gambit_init
+        ;;
+    "update" )
+        gambit_update
+        ;;
+    "configure" )
+        gambit_configure
+        ;;
+    "make" )
+        gambit_make
+        ;;
+    "install" )
+        gambit_install
+        ;;
+    "clean" )
+        gambit_clean
+        ;;
+    "realclean" )
+        gambit_realclean
+        ;;
+    "" )
+        gambit
+        ;;
+    * )
+        echo "Unknown gambit option : $1"
+        return 1
+        ;;
     esac
 }
 
@@ -103,15 +103,15 @@ jobs () {
 
 host () {
     if [ ! -n "${GAMBITMULTIHOST:+x}" ] || [ "$GAMBITMULTIHOST" == "0" ]; then
-		echo "--enable-single-host"
+        echo "--enable-single-host"
     fi
 }
 
 display_module_info () {
     echo "$1"
     if [ -d "$2" ]; then
-	cd "$2" &&
-	git log -1
+        cd "$2" &&
+        git log -1
     fi
 }
 
@@ -121,46 +121,49 @@ display_info () {
 
 while getopts "l" OPTION; do
     case $OPTION in
-	"l" )
-	    UPDATE_SUBMODULES="false"
-	    ;;
+    "l" )
+        UPDATE_SUBMODULES="false"
+        ;;
     esac
 done
 
 shift $((OPTIND-1))
 
 case "$1" in
-	"gambit" )
-		gambit_dispatch $2
-		exit
-		;;
+    "gambit" )
+        gambit_dispatch $2
+        exit
+        ;;
 
-	"info" )
-		display_info
-		exit
-		;;
+    "deploy" )
+        deploy
+        exit
+        ;;
 
-	"environment" )
-		echo "REL: $REL"
-		echo "ABS: $ABS"
-		echo "GAMBITSOURCE: $GAMBITSOURCE"
-		echo "GAMBITINSTALL: $GAMBITINSTALL"
-		echo "GSC: $GSC"
-		echo "SCM: $SCM"
-		echo $(host)
-		exit
-		;;
+    "info" )
+        display_info
+        exit
+        ;;
+
+    "environment" )
+        echo "REL: $REL"
+        echo "ABS: $ABS"
+        echo "GAMBITSOURCE: $GAMBITSOURCE"
+        echo "GAMBITINSTALL: $GAMBITINSTALL"
+        echo "GSC: $GSC"
+        echo "SCM: $SCM"
+        echo $(host)
+        exit
+        ;;
 esac
 
 if [ ! -f "$GSC" ]; then
-	gambit
+    gambit
 fi
 
 if [ ! -f "$GSC" ]; then
-	echo "Unable to find ./foreign/gambit/bin/gsc"
-	exit 1
+    echo "Unable to find ./foreign/gambit/bin/gsc"
+    exit 1
 fi
 
-#echo "$GSC" -:="$GAMBITINSTALL" -i "$SCM" "$@"
-#exit
 exec "$GSC" -:="$GAMBITINSTALL" -i "$SCM" "$@"
