Fix code in previous commit

diff --git a/jaz b/jaz
--- a/jaz
+++ b/jaz
@@ -11,6 +11,10 @@ if [ -z "$GAMBITDIR" ]; then
     GSC="gsc"
 else
     GSC="$GAMBITDIR/bin/gsc"
+    if [ ! -f "$GSC" ]; then
+        echo "Unable to find $GAMBITDIR/bin/gsc"
+        exit 1
+    fi
 fi
 
 SCM="$REL/kernel/jaz.scm"
@@ -42,10 +46,5 @@ case "$1" in
         exit
         ;;
 esac
-
-if [ ! -f "$GSC" ]; then
-    echo "Unable to find $GAMBITDIR/bin/gsc"
-    exit 1
-fi
 
 exec "$GSC" -:="$GAMBITDIR" -i "$SCM" "$@"
